### ISSUE TITLE
comment/uncomment shortcut

### ISSUE THREAD

**Issue by dschick** [jupyterlab/jupyterlab-shortcutui#34]
thanks for the great extension!
Would it be possible to add a comment/uncomment shortcut as well?

**Comment by NoahStapp** [comment]
Hi @dschick,

Can you be more specific as to what you mean by a comment/uncomment shortcut? Commenting and uncommenting where exactly?

**Comment by dschick** [comment]
@NoahStapp there is actually a jupyter notebook extension
https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/comment-uncomment
So I would like to comment/uncomment code in the notebook cells with a shortcut like in spyder, etc

**Comment by NoahStapp** [comment]
In notebooks the shortcut Control-Slash block comments code. Do you want to be able to change it, or are you looking for that command in general?

**Comment by dschick** [comment]
I actually would like to change that command, because on a non-english keyboard "slash" is not directly available which makes it hard to use this shortcut

**Comment by Lef-F** [comment]
Same here! On the Swedish keyboard you have to press `Shift + 7` to get `/` and of course pressing `Ctrl + Shift + 7` does not work.

**Comment by jasongrout** [comment]
FYI, these shortcuts are defined in the codemirror setup: https://github.com/jupyterlab/jupyterlab/blob/156a569cae094edebfbd7a4a7a18aeccbeec1705/packages/codemirror/src/factory.ts#L24-L25 and https://github.com/jupyterlab/jupyterlab/blob/156a569cae094edebfbd7a4a7a18aeccbeec1705/packages/codemirror/src/factory.ts#L34-L35

**Comment by jasongrout** [comment]
In particular, these don't use the jupyterlab application-wide keyboard shortcut system, so changing these shortcuts would require some work in JupyterLab. Could you open an issue in JupyterLab about changing these shortcut keys?

**Comment by Asutu** [comment]
Also struggled a bit with this, and thought this might be useful to others.

In a MacBook Pro with a Portuguese keyboard (that uses `Cmd + Shift + 7` to toggle comments on Sublime Text 3), by trial and error figured that `Ctrl + -` works in JupyterLab.

**Comment by gustnt** [comment]
@dschick  were you able to use the shortcut in non-English keyboard?

**Comment by dschick** [comment]
@gustnt nope.
@jasongrout I linked this issue to https://github.com/jupyterlab/jupyterlab/issues/4778
So we could close it here I guess?

**Comment by afshin** [comment]
Cheers! Thanks for cross-referencing, @dschick. Let's close it here.
