### ISSUE TITLE
Rendered shortcuts assume you are using a Mac

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterlab/jupyterlab-shortcutui#36]
The shortcuts that use the `Accel` key are rendered as `Cmd`, or ⌘

**Comment by NoahStapp** [comment]
Hi Ian,
 
How does the command palette handle Accel keys on windows? Does it display it as Control or the Windows key?

**Comment by NoahStapp** [comment]
This should be fixed in the most recent version, can you confirm?

**Comment by ian-r-rose** [comment]
Thanks! I just checked, and things seem to be working as expected.

Phosphor just today exposed a new function in phosphorjs/phosphor#358 to automatically render a keyboard shortcut (with all the mac/windows/linux stuff handled automatically). If you want to remove the responsibility of handling that logic yourself, you may want to investigate using that.

**Comment by ian-r-rose** [comment]
Closing as fixed.
