### ISSUE TITLE
Add option to modify the built-in search bar command (Command/Control + F)

### ISSUE THREAD

**Issue by basnijholt** [jupyterlab/jupyterlab-shortcutui#4]
It would be really great to be able to modify the shortcut `Command + F` or `Control + F` to something else such that it does not interfere with the browser's search.

This is also an issue here https://github.com/jupyterlab/jupyterlab/issues/4730.

**Comment by jennalandy** [comment]
Hi @basnijholt, the keyboard shortcut command F is handled by code mirror and cannot be fixed by this extension. We see you’ve opened an issue on Jupyter Lab as well, someone should help you there!

**Comment by basnijholt** [comment]
Thanks for your reply!

> keyboard shortcut command F is handled by code mirror and cannot be fixed by this extension

In that case, I'll close the issue here.
