### ISSUE TITLE
Conflicting Dependencies with newest jupyter lab version

### ISSUE THREAD

**Issue by idoDavid** [jupyterlab/jupyterlab-shortcutui#44]
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=0.18.0 <0.19.0 @jupyterlab/application
>=0.19.1 <0.20.0        >=0.18.0 <0.19.0 @jupyterlab/apputils
The command '/bin/sh -c jupyter labextension install @jupyterlab/shortcutui' returned a non-zero code: 1

**Comment by cocoaaa** [comment]
I'm also wondering if there's an update on this. thank you!

**Comment by BharatKambalur** [comment]
Since the current master works correctly with JupyterLab 0.19.X and the package.json file has been updated to reflect this, can this node package to published to npm?

**Comment by Rabeez** [comment]
Still getting this. Has the package not been updated on npm?

**Comment by consideRatio** [comment]
/cc: @jasongrout, I ended up here after following setup instructions https://github.com/jupyterlab/scipy2019-jupyterlab-tutorial

**Comment by ArcticSnow** [comment]
Just ran in the same issue:

```shell
user@host:~$ jupyter labextension install @jupyterlab/shortcutui
Node v8.10.0

> /usr/bin/npm pack @jupyterlab/shortcutui
jupyterlab-shortcutui-0.3.1.tgz

Errored, use --debug for full output:
ValueError: This extension does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=0.18.0 <0.19.0 @jupyterlab/application
>=0.19.1 <0.20.0        >=0.18.0 <0.19.0 @jupyterlab/apputils

```

**Comment by cocoaaa** [comment]
Any updates on this, please?

**Comment by notuntoward** [comment]
I have the same problem.  Is this extension abandoned?

**Comment by wonsjb** [comment]
I've created a push request that should update the dependencies to the latest version of jupyterlab. Still far from prefect, but at least it now shows all the shortcuts, and has some limited update capabilities.

**Comment by afshin** [comment]
Version 0.4.0 supports JupyterLab 1.x now!
