### ISSUE TITLE
run-in-console Shortcut Missing

### ISSUE THREAD

**Issue by jtelleriar** [jupyterlab/jupyterlab-shortcutui#51]
run-in-console Shortcut is missing:

```
{
            "command": "notebook:run-in-console",
            "keys": [
                "Ctrl Enter"
            ],
            "selector": ".jp-Notebook.jp-mod-editMode"
        }

```

**Comment by afshin** [comment]
I think what's happening is that JupyterLab does not ship with a default shortcut for that command. And if you add a custom shortcut for it, it appears that it does not show up in the shortcut editor.
