### ISSUE TITLE
UI stops working if user shortcuts are present

### ISSUE THREAD

**Issue by stefansimik** [jupyterlab/jupyterlab-shortcutui#59]
UI works correctly with default shortcut settings in Jupyterlab.

If one edits keybord shortcuts via:
**Settings menu -> Advanced Settings Editor -> Keyboard shortcuts**
and adds some user settings like:
```
{
    "shortcuts": [
        {
            "command": "runmenu:run",
            "keys": [
                ""
            ],
            "selector": "[data-jp-code-runner]"
        },    
        {
            "command": "runmenu:restart-and-run-all",
            "keys": [
                "Shift Enter"
            ],
            "selector": "[data-jp-code-runner]"
        }
    ]
}
```

then this UI stops working completely - i.e. nothing opens after this UI is invoked.
When I rollback user preferences back to defaults, then UI starts working and opens again.

Expected behavior:
UI should work also with custom user-shortcuts and display them correctly.

My configuration:

- Windows 10 latest
- Chrome latest
- Jupyterlab version: 2.1.0

**Comment by yongrenjie** [comment]
I think this has to do only with certain user-settings. I have not tried your example but you may want to figure out if it's just one of them.

Personally, I have noticed this bug when disabling all shortcuts for a particular item.

**Comment by TejasAvinashShetty** [comment]
Maybe the shift +enter shortcut is also used by some another item?

**Comment by TejasAvinashShetty** [comment]
Maybe the selector has to be a body. I tried this and it ran beautifully.
```javascript
{
    "shortcuts": [
        {
            "command": "notebook:run-all-cells",
            "keys": [
                "Ctrl Shift M"
            ],
            "selector": "body"
        },
        {
            "command": "notebook:run-all-above",
            "keys": [
                "Ctrl Shift A"
            ],
            "selector": "body"
        },
        {
            "command": "notebook:run-all-below",
            "keys": [
                "Ctrl Shift B"
            ],
            "selector": "body"
        }
    ]
}
```
