### ISSUE TITLE
shortcutui@0.5.0 not compatible with jupyterlab V1.0.0

### ISSUE THREAD

**Issue by antvig** [jupyterlab/jupyterlab-shortcutui#60]
When installing the V0.5, the Keyboard Shortcut Editor disappeared from settings.

With V0.4, it works fine.

**Comment by afshin** [comment]
Yes. The shortcut UI extension v. 0.5.x is meant to run with JupyterLab 2+ and is indeed incompatible with JupyterLab 1.x

Sorry for any confusion!
